<?php

$data = [
    ["id" => 1, "name" => "Akhtar", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "JAVA", "gender" => "Male", "degree" => "BCA"],
    ["id" => 2, "name" => "Sohel", "age" => "22", "city" => "Ahmedabad", "state" => "Gujarat", "country" => "India", "subject" => "PHP", "gender" => "Male", "degree" => "MCA"],
    ["id" => 3, "name" => "Manish", "age" => "23", "city" => "Surat", "state" => "Gujarat", "country" => "India", "subject" => ".NET", "gender" => "Male", "degree" => "BCA"],
    ["id" => 4, "name" => "Fardeen", "age" => "22", "city" => "Ahmedabad", "state" => "Gujarat", "country" => "India", "subject" => "JAVA", "gender" => "Male", "degree" => "MCA"],
    ["id" => 5, "name" => "Uday", "age" => "20", "city" => "Sihor", "state" => "Gujarat", "country" => "India", "subject" => "PHP", "gender" => "Male", "degree" => "MSC"],
    ["id" => 6, "name" => "Karan", "age" => "20", "city" => "Rajkot", "state" => "Gujarat", "country" => "India", "subject" => "Android", "gender" => "Male", "degree" => "BCA"],
    ["id" => 7, "name" => "Ajay", "age" => "21", "city" => "Jamnagar", "state" => "Gujarat", "country" => "India", "subject" => "SEO", "gender" => "Male", "degree" => "MBA"],
    ["id" => 8, "name" => "Dhruv", "age" => "23", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "JavaScript", "gender" => "Male", "degree" => "MCA"],
    ["id" => 9, "name" => "Kiran", "age" => "22", "city" => "Palanpur", "state" => "Gujarat", "country" => "India", "subject" => "Python", "gender" => "Male", "degree" => "BCA"],
    ["id" => 10, "name" => "Jyoti", "age" => "22", "city" => "Mumbai", "state" => "Maharashtra", "country" => "India", "subject" => "PHP", "gender" => "Female", "degree" => "MCA"],
    ["id" => 11, "name" => "Vidhi", "age" => "20", "city" => "Ahmedabad", "state" => "Gujarat", "country" => "India", "subject" => "Python", "gender" => "Female", "degree" => "MCA"],
    ["id" => 12, "name" => "Aniket", "age" => "24", "city" => "Patan", "state" => "Gujarat", "country" => "India", "subject" => "JAVA", "gender" => "Male", "degree" => "MSC"],
    ["id" => 13, "name" => "Vishwajeet", "age" => "25", "city" => "Botad", "state" => "Gujarat", "country" => "India", "subject" => ".NET", "gender" => "Male", "degree" => "BSC"],
    ["id" => 14, "name" => "Swati", "age" => "23", "city" => "Ahmedabad", "state" => "Gujarat", "country" => "India", "subject" => "HTML", "gender" => "Female", "degree" => "BSC"],
    ["id" => 15, "name" => "Anjali", "age" => "22", "city" => "Gandhinagar", "state" => "Gujarat", "country" => "India", "subject" => "PHP", "gender" => "Female", "degree" => "MCA"],
    ["id" => 16, "name" => "Uvesh", "age" => "20", "city" => "Botad", "state" => "Gujarat", "country" => "India", "subject" => "Android", "gender" => "Male", "degree" => "BCA"],
    ["id" => 17, "name" => "Preet", "age" => "22", "city" => "Rajkot", "state" => "Gujarat", "country" => "India", "subject" => "Flutter", "gender" => "Male", "degree" => "BSC"],
    ["id" => 18, "name" => "Jaimin", "age" => "22", "city" => "Jaipur", "state" => "Rajasthan", "country" => "India", "subject" => ".NET", "gender" => "Male", "degree" => "MCA"],
    ["id" => 19, "name" => "Aarti", "age" => "19", "city" => "Ahmedabad", "state" => "Gujarat", "country" => "India", "subject" => "PHP", "gender" => "Female", "degree" => "BSC"],
    ["id" => 20, "name" => "Hiral", "age" => "18", "city" => "Gandhinagar", "state" => "Gujarat", "country" => "India", "subject" => "Android", "gender" => "Female", "degree" => "MCA"],
    ["id" => 21, "name" => "Shyam", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 22, "name" => "Anuj", "age" => "20", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 23, "name" => "Kishor", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 24, "name" => "Pruthvi", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 25, "name" => "Tripti", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 26, "name" => "Drashti", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 27, "name" => "Megha", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 28, "name" => "Akash", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 29, "name" => "Darshan", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
    ["id" => 30, "name" => "Darshan", "age" => "22", "city" => "Bhavnagar", "state" => "Gujarat", "country" => "India", "subject" => "NODE", "gender" => "Male", "degree" => "BCA"],
];
